/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeedbackRequest { 'text' : string, 'timestamp' : Time }
export interface MoodEntry { 'timestamp' : Time, 'rating' : bigint }
export interface OnboardingInfo {
  'role' : UserRoleSetting,
  'preferences' : Preferences,
  'preferredName' : [] | [string],
}
export interface Preferences {
  'sleepTime' : bigint,
  'wakeTime' : bigint,
  'goals' : Array<string>,
  'reminderFrequency' : bigint,
}
export interface Reminder {
  'id' : bigint,
  'isRecurring' : boolean,
  'time' : bigint,
  'description' : string,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'onboardingInfo' : [] | [OnboardingInfo],
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRoleSetting = { 'other' : null } |
  { 'elder' : null } |
  { 'professional' : null } |
  { 'homemaker' : null } |
  { 'student' : null };
export interface WellnessEntry { 'hydration' : bigint, 'sleepHours' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReminder' : ActorMethod<[string, bigint, boolean], Reminder>,
  'addWellnessEntry' : ActorMethod<[WellnessEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createTask' : ActorMethod<[string], Task>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getOnboardingInfo' : ActorMethod<[Principal], [] | [OnboardingInfo]>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserFeedbackRequests' : ActorMethod<[], Array<FeedbackRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWellnessEntries' : ActorMethod<[], Array<WellnessEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedbackRequest' : ActorMethod<[string], undefined>,
  'submitMood' : ActorMethod<[bigint], undefined>,
  'submitOnboardingInfo' : ActorMethod<[OnboardingInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];