/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'isRecurring' : IDL.Bool,
  'time' : IDL.Nat,
  'description' : IDL.Text,
});
export const WellnessEntry = IDL.Record({
  'hydration' : IDL.Nat,
  'sleepHours' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'timestamp' : Time,
});
export const UserRoleSetting = IDL.Variant({
  'other' : IDL.Null,
  'elder' : IDL.Null,
  'professional' : IDL.Null,
  'homemaker' : IDL.Null,
  'student' : IDL.Null,
});
export const Preferences = IDL.Record({
  'sleepTime' : IDL.Nat,
  'wakeTime' : IDL.Nat,
  'goals' : IDL.Vec(IDL.Text),
  'reminderFrequency' : IDL.Nat,
});
export const OnboardingInfo = IDL.Record({
  'role' : UserRoleSetting,
  'preferences' : Preferences,
  'preferredName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'onboardingInfo' : IDL.Opt(OnboardingInfo),
  'createdAt' : Time,
});
export const MoodEntry = IDL.Record({ 'timestamp' : Time, 'rating' : IDL.Nat });
export const FeedbackRequest = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReminder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [Reminder], []),
  'addWellnessEntry' : IDL.Func([WellnessEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createTask' : IDL.Func([IDL.Text], [Task], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getOnboardingInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(OnboardingInfo)],
      ['query'],
    ),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserFeedbackRequests' : IDL.Func(
      [],
      [IDL.Vec(FeedbackRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellnessEntries' : IDL.Func([], [IDL.Vec(WellnessEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedbackRequest' : IDL.Func([IDL.Text], [], []),
  'submitMood' : IDL.Func([IDL.Nat], [], []),
  'submitOnboardingInfo' : IDL.Func([OnboardingInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'isRecurring' : IDL.Bool,
    'time' : IDL.Nat,
    'description' : IDL.Text,
  });
  const WellnessEntry = IDL.Record({
    'hydration' : IDL.Nat,
    'sleepHours' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'timestamp' : Time,
  });
  const UserRoleSetting = IDL.Variant({
    'other' : IDL.Null,
    'elder' : IDL.Null,
    'professional' : IDL.Null,
    'homemaker' : IDL.Null,
    'student' : IDL.Null,
  });
  const Preferences = IDL.Record({
    'sleepTime' : IDL.Nat,
    'wakeTime' : IDL.Nat,
    'goals' : IDL.Vec(IDL.Text),
    'reminderFrequency' : IDL.Nat,
  });
  const OnboardingInfo = IDL.Record({
    'role' : UserRoleSetting,
    'preferences' : Preferences,
    'preferredName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'onboardingInfo' : IDL.Opt(OnboardingInfo),
    'createdAt' : Time,
  });
  const MoodEntry = IDL.Record({ 'timestamp' : Time, 'rating' : IDL.Nat });
  const FeedbackRequest = IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReminder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [Reminder], []),
    'addWellnessEntry' : IDL.Func([WellnessEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createTask' : IDL.Func([IDL.Text], [Task], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getOnboardingInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(OnboardingInfo)],
        ['query'],
      ),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserFeedbackRequests' : IDL.Func(
        [],
        [IDL.Vec(FeedbackRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellnessEntries' : IDL.Func([], [IDL.Vec(WellnessEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedbackRequest' : IDL.Func([IDL.Text], [], []),
    'submitMood' : IDL.Func([IDL.Nat], [], []),
    'submitOnboardingInfo' : IDL.Func([OnboardingInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };